Catalog_dir: '/home/alab_student/Tim/Projects/Catalogs/Skymap_Catalogs/'
Out_dir: '/home/alab_student/Tim/Projects/MeV_Blazars/Outputs/JOINED_BG_Source_Maps/'

Out_name: 'JOINED_BG_Source_Map2'

Map_Energy: '0.2-5.0'
E_min: '0.2'
E_max: '5.0' 
Energy_Units: 'Erg'
Flux_Units: 'Erg cm^-2 s^-1'

BG_Catalog: 'data_allsky_cgb_0.2to5.0MeV_SMM.fits'
BG_Data: 'SMM'
BG_Columns: 
  BG_Flux: 'T'

Source_Catalog: 'CGrB_Maps_Point_Source.fits'
Source_Columns:
  RA: 'RA'
  DEC: 'DEC'
  Source_Flux: 'Flux_0_2to10'
