Catalog_dir: '/home/alab_student/Tim/Projects/Catalogs/Skymap_Catalogs/'
Out_dir: '/home/alab_student/Tim/Projects/MeV_Blazars/Outputs/CGrB_Maps/'

Out_name: 'CGrB_Flux_Map_COMPTEL'

Catalog_Name: 'data_allsky_cgb_0.1to1.0MeV.fits'

E_min: '0.1'
E_max: '1.0' 