Catalog_dir: '/home/alab_student/Tim/Projects/Catalogs/'

Out_dir: '/home/alab_student/Tim/Projects/MeV_Blazars/Outputs/LF_Outputs/'

Catalog_Name: 'Model_Param_LF.fits'

columns:
  source_name: 'Name'
  source_class: 'Class'
  source_model: 'Model'
  source_redshift: 'Redshift'
  reference_energy: 'E0'
  reference_flux: 'N0'

  LP_alpha: 'LP_Alpha'
  LP_beta: 'LP_Beta'

  SBPL_Index1: 'SBPL_Index1'
  SBPL_Index2: 'SBPL_Index2'
  SBPL_Break_Energy: 'SBPL_Break_Energy'
  SBPL_Beta: 'SBPL_Beta'



  

