Catalog_dir: '/home/alab_student/Tim/Projects/Catalogs/Skymap_Catalogs/'
Out_dir: '/home/alab_student/Tim/Projects/MeV_Blazars/Outputs/HEALPIX_Maps/'

Out_name: 'CGrB_Map_Point_Source'

Catalog_Name: 'CGrB_Maps_Point_Source.fits'

Map_Energy: '10-100'
Energy_Units: 'MeV'
Flux_Units: 'MeV cm^-2 s^-1'

Columns:
  RA: 'RA'
  DEC: 'DEC'
  Flux: 'Flux_10to100'
