Catalog_dir: '/home/alab_student/Tim/Projects/Catalogs/'
Out_dir: '/home/alab_student/Tim/Projects/MeV_Blazars/Outputs/HEALPIX_Maps/'

Out_name: 'MeV_HEALPIX_Map_Matched'

Catalog_Name: 'Masked_Matched_Flux_Map.fits'

Map_Energy: '100'
Energy_Units: 'MeV'
Flux_Units: 'MeV cm^-2 s^-1'

Columns:
  RA: 'RA'
  DEC: 'DEC'
  Flux: 'MeV_Flux_100.0'
